name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: moonrepo/setup-moon-action@v1

      - name: Run CI
        run: moon ci

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: moon_toolchain_nix.wasm
          path: moon_toolchain_nix.wasm
          if-no-files-found: error
