name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt, clippy
          cache-base: master

      - name: Setup toolchain
        run: |
          rustup target add wasm32-wasip1

      - name: Check formatting
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: cargo test

      - name: Build plugin
        run: cargo build --target wasm32-wasip1 --release

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: moon_toolchain_nix-${{ matrix.os }}.wasm
          path: target/wasm32-wasip1/release/moon_toolchain_nix.wasm
          if-no-files-found: error