name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  pull-requests: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - uses: moonrepo/setup-toolchain@v0

      - name: Run CI
        run: moon ci fmt build

      - uses: moonrepo/run-report-action@v1
        if: github.event_name == 'pull_request'
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: moon_toolchain_nix.wasm
          path: moon_toolchain_nix.wasm
          if-no-files-found: error
