name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - run: nix profile install nixpkgs#devenv

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - run: moon ci format build
        env:
          MOON_LOG: debug

      - uses: actions/upload-artifact@v4
        with:
          name: moon_toolchain_nix.wasm
          path: ./target/wasm32-wasip1/release/moon_toolchain_nix.wasm
          if-no-files-found: error
