name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - run: nix profile install nixpkgs#devenv

      - uses: moonrepo/setup-toolchain@v0

      - run: |
          moon ci build-release
          sha256sum target/wasm32-wasip1/release/moon_toolchain_nix.wasm > target/wasm32-wasip1/debug/moon_toolchain_nix.wasm.sha256

      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
          files: |
             target/wasm32-wasip1/release/moon_toolchain_nix.wasm
             target/wasm32-wasip1/debug/moon_toolchain_nix.wasm.sha256
