name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          cache-base: master

      - name: Setup toolchain
        run: |
          rustup target add wasm32-wasip1

      - name: Build plugin
        uses: moonrepo/build-wasm-plugin@v0
        id: plugin
        with:
          target: wasm32-wasip1

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
          files: ${{ steps.plugin.outputs.artifact-path }}